### ISSUE TITLE
Not possible to run or install fim-1.2.3 in new system

### ISSUE THREAD

**Issue by lpvm** [evrignaud/fim#26]
When using the  `1.2.3-distribution`, 

```
$ /usr/local/bin/fim/fim fdup
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.rits.cloning.Cloner (file:/usr/local/bin/fim/bin/fim-1.2.3.jar) to field java.util.TreeSet.m
WARNING: Please consider reporting this to the maintainers of com.rits.cloning.Cloner
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.UnsupportedOperationException: Path not associated with default file system.
        at java.base/java.nio.file.Path.toFile(Path.java:771)
        at org.fim.internal.SettingsManager.load(SettingsManager.java:62)
        at org.fim.internal.SettingsManager.<init>(SettingsManager.java:49)
        at org.fim.command.AbstractCommand.checkHashMode(AbstractCommand.java:51)
        at org.fim.command.FindDuplicatesCommand.execute(FindDuplicatesCommand.java:48)
        at org.fim.Fim.run(Fim.java:258)
        at org.fim.Fim.main(Fim.java:75)
```

When trying to install from sources:

```
[INFO] Copying file images/hands-on-little.png
Jul 09, 2020 9:15:02 PM org.asciidoctor.internal.JRubyAsciidoctor renderFile
SEVERE: (RuntimeError) asciidoctor: FAILED: /home/lupe/recolhidos/fim-1.2.3/src/main/asciidoc/slides/fr.adoc: Failed to load AsciiDoc document - Could not find a converter to handle transform: inline_quoted
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.690 s
[INFO] Finished at: 2020-07-09T21:15:02+01:00
[INFO] Final Memory: 49M/118M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.5:process-asciidoc (generate-slides) on project fim: Execution generate-slides of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.5:process-asciidoc failed: org.jruby.exceptions.RaiseException: (RuntimeError) asciidoctor: FAILED: /home/lupe/recolhidos/fim-1.2.3/src/main/asciidoc/slides/fr.adoc: Failed to load AsciiDoc document - Could not find a converter to handle transform: inline_quoted -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch. [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

As I don't know Java or maven, I'd appreciate some step-by-step help on how to solve this issue.
I'm using openjdk11 on Linux 64 bits.

**Comment by OcelotNat** [comment]
Work on Ubuntu 21.10 :
`apt install openjdk-8-jre`
`JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre/" PATH=$JAVA_HOME/bin/:$PATH fim fdup`
